services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
        - ./:/var/www/html/
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - app
  #PHP Service
  app:
    build:
        context: ./
        dockerfile: Dockerfile
        args:
          USER: app_user
          UID: 1000
    container_name: app
    restart: always
    tty: true
    # command: sh -c "php artisan migrate"
    volumes:
       - ./:/var/www/html/
       - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - sqldb
    networks:
      - app-network

  #MySQL Service
  sqldb:
    image: mysql:8.1
    container_name: sqldb
    command:
      - --authentication_policy=mysql_native_password
    restart: unless-stopped
    tty: true
    volumes:
      - ./sql-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
